---
moodle_host: 192.168.98.105
moodle_url: "http://{{moodle_host}}"
moodle_archive_url: https://download.moodle.org/download.php/direct/stable37/moodle-3.7.tgz
download_dir: /home/vagrant

# bei Benutzung von edu-sharing v4.2 bitte entsprechend das plugin 4.2 benutzen
edu_sharing_plugin_dir: "{{ download_dir }}/plugin-moodle-4.1.2"
# edu_sharing_plugin_dir: "{{ download_dir }}/plugin-moodle-4.2"
moodle_data_dir: /var/moodledata
moodle_root_dir: /var/www

moodle_admin_user: admin
moodle_admin_password: asd456
moodle_admin_email: ab@c.de

moodle_fullname: "Moodle-Test-BOX"
moodle_shortname: "moodle-box"
moodle_summary: "Eine_virtuelle_Box_um_Moodle_zu_testen."

mariadb_port: 3306
moodle_db:
  name: moodle
  user: moodle
  password: moodle

edu_sharing_host: 192.168.98.101
edu_sharing_base_domain: http://192.168.98.101
edu_sharing_url: "{{ edu_sharing_base_domain }}/edu-sharing"

# bei Benutzung von edu-sharing v4.2 bitte die das Plugin v4.2 benutzen
edusharing_plugin_url: https://github.com/edu-sharing/plugin-moodle/archive/4.1.2.tar.gz
# edusharing_plugin_url: https://github.com/edu-sharing/plugin-moodle/archive/4.2.tar.gz

base_dir: "{{ansible_env.HOME}}"