---
moodle_host: 192.168.98.105
moodle_url: "http://{{moodle_host}}"
moodle_archive_url: https://download.moodle.org/download.php/direct/stable400/moodle-4.0.1.tgz
download_dir: /home/vagrant

moodle_data_dir: /var/moodledata
moodle_root_dir: /var/www

moodle_admin_user: admin
moodle_admin_password: asd456
moodle_admin_email: ab@c.de

moodle_fullname: "Moodle-Test-BOX"
moodle_shortname: "moodle-box"
moodle_summary: "Eine_virtuelle_Box_um_Moodle_zu_testen."

mariadb_port: 3306
mariadb_root_pw: xxx
moodle_db:
  name: moodle
  user: moodle
  password: moodle

install_edu_sharing_plugin: false
edu_sharing_host: 192.168.98.101
edu_sharing_base_domain: http://192.168.98.101
edu_sharing_url: "{{ edu_sharing_base_domain }}/edu-sharing"
edu_sharing_version: "5.0"  # version of edu-sharing that should be connected. for example: 4.1.2, 4.2 or 5.0 - see https://github.com/edu-sharing/plugin-moodle/releases

edu_sharing_plugin_dir: "{{ download_dir }}/plugin-moodle-{{ edu_sharing_version }}"
# edu_sharing_plugin_dir: "{{ download_dir }}/plugin-moodle-4.2"
edusharing_plugin_url: https://github.com/edu-sharing/plugin-moodle/archive/{{ edu_sharing_version }}.tar.gz
# edusharing_plugin_url: https://github.com/edu-sharing/plugin-moodle/archive/4.2.tar.gz

base_dir: "{{ansible_env.HOME}}"