---
- hosts: moodle
  become: yes
  roles:
    - set-timezone
    - mariadb
    - apache
    - moodle
  tags:
    - root-task

- hosts: moodle
  become: yes
  roles:
    - edu-sharing-plugin
  tags:
    - edu-sharing-plugin